### ISSUE TITLE
How does struct mapping work?

### ISSUE THREAD

**Issue by SharkFourSix** [georgysavva/scany#144]
How does struct mapping work without using tags?

Does it depend on the order of the selected columns? If so, what happens if one executes something like this:

```sql
SELECT * FROM foo WHERE bar = 'baz';
```

**Comment by georgysavva** [comment]
Hi! When you say "tags," do you mean tags in Go struct fields or column tags in your database select statement?

If you don't provide Go struct tags, scany automatically translates your field names to snake case to match the columns in the database. If you don't specify column names in your select statement, the database just returns all the columns in the table with their default name. Note that by default, scany expects that your struct destination has the corresponding struct field for all the selected columns, so in the case of `SELECT * FROM foo WHERE bar = 'baz';`, your Go struct must contain fields for all the columns in the table. Since you can add a new column in a database migration and forget to change your Go code, doing `SELECT * FROM foo WHERE bar = 'baz';` is not advisable. It's always better to list all the needed columns explicitly in your select statement. 

Let me know if you have further questions.

**Comment by SharkFourSix** [comment]
@georgysavva 

Tags are golang specific. 

Anyway, I managed to just use the tags.

But now I'm noticing that my custom struct values don't get their Scan/Value called.

```go
type SomeEnum string

func (e *SomeEnum) Scan(value any) error {}

func (e *SomeEnum) Value()(any, error){
    ....
}
```

Those functions implement: ``sql.Scanner`` and ``sql.Valuer``.

Does the library respect that or it "hijacks" the behavior from the driver?
