### ISSUE TITLE
pgxscan doesn't transform timestamp as it does sqlscan

### ISSUE THREAD

**Issue by B0ER** [georgysavva/scany#146]
My entity file is equal for pgxscan and sqlscan, but for simple db connection through sqlscan works, otherwise for pool (pgxscan) doesn't.

Have a structure, filename is `order.entity.go`
``` go
type OrderEntity struct {
	Id           string  `json:"id"`
	Created_at   *string `json:"created_at"`
	Closed_at    *string `json:"closed_at"`
	Delivered_at *string `json:"delivered_at"`
}
```

SQL query:
sql, args, _ := "SELECT * FROM public.order WHERE user_id = $1"

Attaching two snippet of sending request:

One connection
```go
db, err := sql.Open(sqlProvider, dataSourceName)
// some code
err := sqlscan.Select(context, service.connector, &orders, sql, args...)
```

Pool connection
```go
dbPool, err := pgxpool.New(context, dataSourceName)
// some code
err := pgxscan.Select(context, connector, &orders, sql, args...)
```

Order table has this creation signature and problem with timestamp cast
```sql
CREATE TABLE IF NOT EXISTS public.order (
  id UUID DEFAULT gen_random_uuid() CONSTRAINT idx_order_id PRIMARY KEY,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMP WITHOUT TIME ZONE,
  delivered_at TIMESTAMP WITHOUT TIME ZONE
);
```

I see in the simple connection I used abstract go's database/sql adapter, and in the second variant I have pool object from `pgxpool`.
Changing `*string` type to `*time.Time` helped me, and resolved problem for the pool connection.
Created an issue here as don't believe it should be like now

**Comment by georgysavva** [comment]
Hi, the type conversion is handled by the underlying database library driver. `pgx` and `database/sql`have different behaviors for the timestamp database type. That's why the same code works for you with `sqlscan` but doesn't work with `pgxscan`. Scany just passes your struct fields to the underlying database's `.scan()` method and lets it handle the individual field scanning. Feel free to reopen if you have further questions.
