### ISSUE TITLE
Functions are not supported in queries

### ISSUE THREAD

**Issue by virtumonde** [georgysavva/scany#15]
I am performing the following query using ```pgx```:
```
err := pgxscan.Select(context.Background(), db.pool, &things, `SELECT ST_AsBinary("coordinate") FROM "thing"`)
```
After executing it, I am getting the following error:
```
column: 'st_asbinary': no corresponding field found, or it's unexported in main.SafePlayer
```
It seems that functions are not supported in queries. Is it possible to add this functionality?

**Comment by georgysavva** [comment]
Hi. For scany it doesn’t matter is it a function or a regular field. It works with column names and the column name is `st_asbinary` in that case. The error that you posted means that result rows contain column `st_asbinary`, but your strict doesn't.
I believe you wanted it to be `coordinate` instead. You can fix it by adding an alias in the SQL: 
```sql
SELECT ST_AsBinary("coordinate") AS coordinate FROM "thing"
```

Otherwise, you can add struct tag `db:"st_asbinary"` to the one of `main.SafePlayer` fields, but the solution above makes more sense for me.

**Comment by virtumonde** [comment]
@georgysavva This works perfectly. Thanks for your help!
