### ISSUE TITLE
Add scanning for a single row

### ISSUE THREAD

**Issue by nickelghost** [georgysavva/scany#28]
Hi, thanks for creating this library, it's very useful!

However, I think it'd be great to add a function (or change behaviour of `ScanOne`) so we can pass the `row` type. Right now, when implementing scany, all code that uses `QueryRow` has to switch to using `Query` because none of the functions support scanning sql's `row`, only `rows`.

**Comment by georgysavva** [comment]
Hi. Thanks for opening this issue. Could you please provide an example of what are you trying to achieve?

**Comment by nickelghost** [comment]
Sure. Basically, I had this code:
```go
err = n.DB.QueryRow(context.Background(), sql, args...).Scan(
    &news.ID,
    &news.Title,
    &news.Subtitle,
    &news.Content,
    &news.Category,
    &news.Slug,
    &news.PublishedAt,
    &news.CreatedAt,
    &news.UpdatedAt,
)
```

And I'd like to be able to implement scany for it to look like this:

```go
row := n.DB.QueryRow(context.Background(), sql, args...)
var news entity.News
err = pgxscan.ScanOneRow(&news, row)
```

But, since all scany's methods require rows, and don't support row, I had to implement it like this:

```go
rows, err := n.DB.Query(context.Background(), sql, args...)
if err != nil {
    return nil, err
}
var news entity.News
err = pgxscan.ScanOne(&news, rows)
```

Which requires more code and isn't as clear (because we query for multiple rows, but only use one).

**Comment by georgysavva** [comment]
You can do it even simpler, using the `pgxscan.Get()` function: 
```go
var news entity.News
err := pgxscan.Get(context.Background(), n.DB, &news, sql, args...)
...
```
For more detail see [docs](https://pkg.go.dev/github.com/georgysavva/scany@v0.2.7/pgxscan#Get) for the `.Get()` function.

Scany doesn't work with `Row` type intentionally, because it doesn't expose enough information to do the mapping. 
And generally, there should be no need to pass a `Row` type to scany, since it provides all helper functions that you would need. 
I hope it helps!

**Comment by nickelghost** [comment]
I won't be able to use `pgxscan.Get()` in every situation, but fair enough! Thanks!
