### ISSUE TITLE
join examples?

### ISSUE THREAD

**Issue by krazik-intuit** [georgysavva/scany#35]
any examples on how to perform a join? 

here is how sqlx did it: https://snippets.aktagon.com/snippets/757-how-to-join-two-tables-with-jmoiron-sqlx

**Comment by krazik-intuit** [comment]
actually looks to work similarly, (a comma got me again in the `db` tag), tho leaving this here for others since docs don't cover

**Comment by georgysavva** [comment]
Hi and thank you for opening this issue. 
Indeed, I didn't cover the join case in the docs explicitly, because the join isn't the responsibility of the scany library. 
I provided explanations of how to reuse structs with scany (this is what you would want to do in case of a join) in that docs section: https://pkg.go.dev/github.com/georgysavva/scany@v0.2.8/dbscan#hdr-Reusing_structs. Basically this section explains all mechanisms that one would one to use in case of a join.

But I think you are right, and having a high-level example of a join that showcases real-world usage would be great. 
I will think of a way of adding it to the docs or as a separate article. Thanks!

**Comment by georgysavva** [comment]
> Waiting for examples about how to create backref and etc

@arkady-bagdasarov Could you please explain in more detail what kind of examples you need?

**Comment by arkady-bagdasarov** [comment]
@georgysavva for example, i how to implement has many relations? [example from gorm](https://gorm.io/docs/has_many.html)

**Comment by georgysavva** [comment]
> @georgysavva for example, i how to implement has many relations? [example from gorm](https://gorm.io/docs/has_many.html)

@arkady-bagdasarov scany isn't an ORM. It doesn't work as `gorm`. You can't _implement_ `many to many` or `one to many` relations with scany, because scany knows nothing about your relations and schema. The only way how scany can help you is by reusing your structs when you write your `one to many`/`many to many` queries with a `JOIN`.

Please check that docs section for details on how to reuse your structs with scany: https://pkg.go.dev/github.com/georgysavva/scany@v0.2.8/dbscan#hdr-Reusing_structs

**Comment by arkady-bagdasarov** [comment]
Thanks!

**Comment by Metalscreame** [comment]
@georgysavva  Hi!

Question related to Joins examples.
```
SELECT o.id, o.name,  FROM table AS o 
```
Will scan work in this case (using AS)?

**Comment by Metalscreame** [comment]
Thanks for the answer, regarding Joins. Faced today an issue with JOIN query

```
scany: rows contain a duplicate column 'id'
```

```
SELECT 
                o.id, vi.id
 FROM table1 AS o LEFT JOIN table2 AS vi ON o.vi_id = vi.id WHERE o.id = $1
```

I feel that this is regular case to select ids with the same field name from different tables

**Comment by georgysavva** [comment]
Hi! The problem here is that the database translates "o.id" and "vi.id" to the same column name "id" and you need to explicitly alias them to make it work with scany:

SELECT 
                o.id AS "o.id", vi.id AS "vi.id"
 FROM table1 AS o LEFT JOIN table2 AS vi ON o.vi_id = vi.id WHERE o.id = $1

**Comment by Metalscreame** [comment]
so in this case how will structures look like?
```
type Table1 struct {
    ID string `db:"id"
}
type Table2 struct {
    ID string `db:"id"
}
```
```
type Table1 struct {
    ID string `db:"o.id"
}
type Table2 struct {
    ID string `db:"vi.id"
}
```

**Comment by georgysavva** [comment]
Depends on how you combine those to structs into a single one that you pass to scany. You can do it like that:
```go
type Table1 struct {
    ID string `db:"id"
}
type Table2 struct {
    ID string `db:"id"`
}
type Result struct {
    O *Table1 `db:"o"`
    VI *Table2 `db:"vi"`
}
```

**Comment by Metalscreame** [comment]
Oh, thanks, this is a really nice example. Didn't expect it will work this way

**Comment by georgysavva** [comment]
> Oh, thanks, this is a really nice example. Didn't expect it will work this way

@Metalscreame Check out this doc section for more details: https://pkg.go.dev/github.com/georgysavva/scany@v0.2.8/dbscan#hdr-Reusing_structs

**Comment by 0radek** [comment]
I'm struggling to make this work if you don't mind helping me. I have a `SignUpLink` (sign_up_links table) and `Account` (accounts table)

```go
type SignUpLink struct {
	ID        *uuid.UUID
	AccountID *uuid.UUID
	Link      *string
	CreatedAt *time.Time
}
```

```go
type Account struct {
	ID        *uuid.UUID
	Name      *string
	CreatedAt *time.Time
}
```

```go
type SignUpLinkAccount struct {
	Account    *Account    `db:"a"`
	SignUpLink *SignUpLink `db:"sl"`
}
```

I want to do something like this (and handle the issue with duplicate column as mentioned above, but I'm not sure how to go about it)

```
SELECT sl.*, a.*
FROM public.signup_links sl
INNER JOIN public.accounts a ON sl.account_id = a.id
WHERE sl.id = $1;
```

```go
rows, _ := s.db.Query(ctx, stmt, id)

	if err := pgxscan.Scan(signUpLinkAccount, rows); err != nil {
		return nil, newStoreError(err)
	}
```
